attendance/urls.py
from django.conf.urls import patterns, url
from django.contrib import admin

import views

admin.autodiscover()

urlpatterns = patterns(
    '',
    url(
        r'^(?P<pk>\d+)/$',
        views.RecordAttendanceView.as_view(),
        name='record'
    ),

    url(
        r'^csv/(?P<pk>\d+)/$',
        views.AttendanceCSVView.as_view(),
        name='csv'
    ),

    url(
        r'^ajax$',
        views.RecordAttendanceAjaxView.as_view(),
        name='record-ajax'
    ),

    url(
        r'^$',
        views.SessionListView.as_view(),
        name='list'
    ),
)

dojo/urls.py
from django.conf.urls import patterns, url
from django.contrib import admin

import views

admin.autodiscover()

urlpatterns = patterns(
    '',
    url(r'^roles/$', views.RoleView.as_view(), name='roles'),
)

kanri/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings
from django.contrib import admin
from django.conf.urls.static import static

admin.autodiscover()

urlpatterns = patterns(
    '',
    url(r'^admin/', include(admin.site.urls)),
    url(r'^mentors/', include('mentors.urls', namespace='mentors')),
    url(r'^dojo/', include('dojo.urls', namespace='dojo')),
    url(r'^attendance/', include('attendance.urls', namespace='attendance')),
    url(r'^badges/', include('badges.urls', namespace='badges')),

    # Auth
    url(r'^login/', 'django.contrib.auth.views.login', name='login'),

    url(
        r'^logout/',
        'django.contrib.auth.views.logout_then_login',
        name='logout'
    ),

    # Dashboard app collects all other URLs
    url(r'', include('dashboard.urls', namespace='dashboard')),
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

attendance/models.py
from django.db import models


class Attendance(models.Model):
    arrival = models.DateTimeField(
        help_text="When did the ninja arrive?",
        auto_now_add=True,
    )

    sighted_by = models.ForeignKey(
        'mentors.Mentor',
        help_text='Which mentor sighted this Ninja upon arrival and '
                  'ensured their safety and supervision?'
    )

    ninja = models.ForeignKey(
        'ninjas.Ninja',
        help_text='What ninjas is attending?',
    )

    session = models.ForeignKey(
        'dojo.Session',
        help_text='What session is the Ninja attending?',
    )

    def __str__(self):
        return "{s.ninja} attending {s.session}".format(s=self)

ninjas/models/ninja.py
from django.db import models
from django.conf import settings


class Ninja(models.Model):
    MALE = 'M'
    FEMALE = 'F'

    GENDER_CHOICES = (
        (MALE, 'Male'),
        (FEMALE, 'Female'),
    )

    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        blank=True,
        help_text='The user associated with this ninja.',
    )

    gender = models.CharField(
        max_length=1,
        choices=GENDER_CHOICES
    )

    school_year = models.PositiveSmallIntegerField(
        help_text='The ninja\'s school year.'
    )

    laptop = models.BooleanField(
        default=False,
        help_text='Does this ninja have a laptop they can bring with them?'
    )

    allergies = models.CharField(
        max_length=50,
        blank=True,
        help_text='A list of allergies this ninja has.'
    )

    attended_old_dojo = models.BooleanField(
        default=False,
        help_text='The Ninja has attended Dojos before persistent records.'
    )

    parents = models.ManyToManyField(
        'ninjas.Parent',
        help_text='The Ninja\'s listed parent.'
    )

    applied_dojos = models.ManyToManyField(
        'dojo.Term',
        related_name='applied_ninjas',
        help_text="Dojo terms the Ninja has applied to be in."
    )

    enrolled_dojos = models.ManyToManyField(
        'dojo.Term',
        related_name='enrolled_ninjas',
        help_text="Dojo terms the Ninja has enroled in."
    )

    @property
    def age(self):
        return self.school_year + 5

    def supervision_required(self):
        return self.school_year < 6

    def returning(self):
        # in the future, this'll handle old terms too.
        return self.attended_old_dojo

    def not_attended_session(self):
        return (not self.returning()) and (not self.attendance_set.all())

    def __str__(self):
        return self.user.get_full_name()

    returning.boolean = True  # django admin setting
    not_attended_session.boolean = True  # ditto
    supervision_required.boolean = True  # ditto

    class Meta:
        ordering = ['user__first_name']

attendance/forms.py
from django import forms

import models


class AttendanceAjaxForm(forms.ModelForm):
    here = forms.BooleanField(
        required=False
    )

    class Meta:
        model = models.Attendance
        fields = ['ninja', 'session']

attendance/views.py
# coding=utf-8
from __future__ import absolute_import, unicode_literals
from . import forms, models
import csv
import datetime
from django import shortcuts, http
from django.utils import timezone
from django.views import generic
import dojo
import mentors
import ninjas
import StringIO


class SessionListView(generic.TemplateView):

    def get_context_data(self, *args, **kwargs):
        c = super(SessionListView, self).get_context_data(*args, **kwargs)

        mentor = mentors.models.Mentor.objects.get(user=self.request.user)
        # this buffer accounts for sessions running over, taking signups
        # early, etc.
        buff = datetime.timedelta(hours=1)
        now = timezone.now()

        relevant = dojo.models.Session.objects.all()

        if not self.request.user.is_superuser:
            relevant = relevant.filter(
                term__dojo__role__approved_roles=mentor)

        # Sessions happening now.
        c['current'] = relevant.filter(
            start__lt=now + buff,
            finish__gt=now - buff
        )

        # Upcomming sessions
        c['upcomming'] = relevant.filter(
            start__gt=now + buff,
            start__lt=now + datetime.timedelta(days=1),
        )

        # Sessions in the 'distant' future
        c['future'] = relevant.filter(
            start__gt=now + datetime.timedelta(days=1),
        )

        # Old sessions.
        c['old'] = relevant.filter(
            finish__lt=now - buff
        )

        return c

    template_name = 'attendance/list.html'


class AttendanceCSVView(generic.detail.SingleObjectMixin,
                        generic.View):

    model = dojo.models.Term

    def get(self, *args, **kwargs):
        output = StringIO.StringIO()
        term = self.get_object()

        # get regular dojo sessions to report
        sessions = dojo.models.Session.objects.order_by('-start')
        sessions = sessions.filter(term=term)
        sessions = sessions.filter(session_type=dojo.models.Session.REGULAR)

        # Get all ninjas that signed up for term.
        term_ninjas = ninjas.models.Ninja.objects.filter(enrolled_dojos=term)

        # Get the CSV writer ready.
        fields = ['Name', 'Gender', 'School Year']
        for session in sessions:
            fields.append("{date}".format(date=session.start.date()))
        writer = csv.DictWriter(output, fieldnames=fields)
        writer.writeheader()

        # Print for each user.
        for ninja in term_ninjas:
            row = {
                "Name": ninja.user.get_full_name(),
                "Gender": ninja.get_gender_display(),
                "School Year": ninja.school_year
            }
            attendances = models.Attendance.objects.filter(session=sessions, ninja=ninja)
            for attendance in attendances:
                attendance_date = "{date}".format(date=attendance.session.start.date())
                row.update({
                    attendance_date: 'Attended'
                })

            writer.writerow(row)

        return http.HttpResponse(output.getvalue(), content_type="text/csv")


class RecordAttendanceView(generic.ListView):
    template_name = 'attendance/record.html'

    def get_queryset(self, *args, **kwargs):
        self.session = shortcuts.get_object_or_404(
            dojo.models.Session,
            pk=self.kwargs['pk'])

        attn_ninjas = self.session.term.enrolled_ninjas.all()
        return [{
            'ninja': n,
            'attendance': models.Attendance.objects.filter(
                ninja=n, session=self.session)
            } for n in attn_ninjas]

    def get_context_data(self, **kwargs):
        context = super(RecordAttendanceView, self).get_context_data(**kwargs)
        context['session'] = self.session
        context['superuser_override'] = self.superuser_override
        return context

    def dispatch(self, *args, **kwargs):
        self.superuser_override = False

        try:
            self.mentor = mentors.models.Mentor.objects.get(
                user__id=self.request.user.id
            )

            allowed = dojo.models.Session.objects.filter(
                term__dojo__role__approved_roles=self.mentor,
                id=kwargs['pk']
            )
        except mentors.models.Mentor.DoesNotExist:
            allowed = None

        if not allowed:
            if self.request.user.is_superuser:
                self.superuser_override = True
            else:
                return shortcuts.redirect('attendance:list')

        return super(RecordAttendanceView, self).dispatch(*args, **kwargs)


class RecordAttendanceAjaxView(generic.View):
    def post(self, *args, **kwargs):
        form = forms.AttendanceAjaxForm(self.request.POST)
        if form.is_valid():
            if form.cleaned_data['here']:
                att = models.Attendance.objects.create(
                    ninja=form.cleaned_data['ninja'],
                    session=form.cleaned_data['session'],
                    sighted_by=mentors.models.Mentor.objects.get(
                        user=self.request.user))

                att.full_clean()
                att.save()
            else:
                models.Attendance.objects.filter(
                    ninja=form.cleaned_data['ninja'],
                    session=form.cleaned_data['session']
                ).delete()

            return http.JsonResponse({
                'success': True
                })
        else:
            return http.JsonResponse({
                'error': True
                })

attendance/templates/attendance/list.html
{% extends "base.html" %}

{% block site_title %}Attendance{% endblock %}
{% block body_title %}Ninja attendance{% endblock %}

{% block content %}

{% if user.is_superuser %}
    <div class="alert alert-warning">
        <p>As you are a superuser, you may be shown sessions for dojos that you do not belong to. Please be mindful
        when accessing or modifying attendance records of other dojos, as it could compromise the safety and security
        of the dojo.</p>
    </div>
    <hr />
{% endif %}

{% if current %}
    <h2>Current sessions <small>running, starting in the next hour, or finished less than a hour ago.</h2>
    <table class="table bg-success">
        <thead>
            <th>Session</th>
            <th>Time/Date</th>
            <th class="col-md-1"></th>
        </thead>
        <tbody>
            {% for session in current %}
                <tr>
                    <td>
                        {{ session }}<br />
                           <small>{{ session.term.name }} - {{ session.term.dojo }}</small>
                    </td>
                    <td>
                        {{ session.start|date }}
            
                        {% if session.start.date != session.finish.date %}
                             - {{ session.finish|date }}
                        {% endif %}
    
                        <br />
                        <small>{{ session.start|time }} to {{ session.finish|time }} (in {{ session.start|timeuntil }})</small>
                    </td>
                    <td>
                        <a href="{% url 'attendance:record' session.id %}" class="btn btn-primary">Do Attendance</a>   
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endif %}


{% if upcomming %}
    <h2>Upcomming sessions <small>less than a day until start.</h2>
    <table class="table">
        <thead>
            <th>Session</th>
            <th>Time/Date</th>
            <th class="col-md-1"></th>
        </thead>
        <tbody>
            {% for session in upcomming %}
                <tr>
                    <td>
                        {{ session }}<br />
                           <small>{{ session.term.name }} - {{ session.term.dojo }}</small>
                    </td>
                    <td>
                        {{ session.start|date }}
            
                        {% if session.start.date != session.finish.date %}
                             - {{ session.finish|date }}
                        {% endif %}
    
                        <br />
                        <small>{{ session.start|time }} to {{ session.finish|time }} (in {{ session.start|timeuntil }})</small>
                    </td>
                    <td>
                        <a href="{% url 'attendance:record' session.id %}" class="btn btn-primary">Do Attendance</a>   
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endif %}


{% if future %}
    <h2>Future sessions <small>pretty obvious.</h2>
    <table class="table">
        <thead>
            <th>Session</th>
            <th>Time/Date</th>
            <th class="col-md-1"></th>
        </thead>
        <tbody>
            {% for session in future %}
                <tr>
                    <td>
                        {{ session }}<br />
                           <small>{{ session.term.name }} - {{ session.term.dojo }}</small>
                    </td>
                    <td>
                        {{ session.start|date }}
            
                        {% if session.start.date != session.finish.date %}
                             - {{ session.finish|date }}
                        {% endif %}
    
                        <br />
                        <small>{{ session.start|time }} to {{ session.finish|time }} (in {{ session.start|timeuntil }})</small>
                    </td>
                    <td>
                        <a href="{% url 'attendance:record' session.id %}" class="btn btn-primary">Do Attendance</a>   
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endif %}


{% if old %}
    <h2>Old sessions <small>if you need to retroactively change attendance details.</h2>
    <table class="table">
        <thead>
            <th>Session</th>
            <th>Time/Date</th>
            <th class="col-md-1"></th>
        </thead>
        <tbody>
            {% for session in old %}
                <tr>
                    <td>
                        {{ session }}<br />
                           <small>{{ session.term.name }} - {{ session.term.dojo }}</small>
                    </td>
                    <td>
                        {{ session.start|date }}
            
                        {% if session.start.date != session.finish.date %}
                             - {{ session.finish|date }}
                        {% endif %}
    
                        <br />
                        <small>{{ session.start|time }} to {{ session.finish|time }} ({{ session.start|timesince }} ago)</small>
                    </td>
                    <td>
                        <a href="{% url 'attendance:record' session.id %}" class="btn btn-primary">Do Attendance</a>   
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endif %}

{% endblock %}

attendance/templates/attendance/record.html
{% extends "base.html" %}

{% load bootstrap3 %}
{% load staticfiles %}

{% block site_title %}Attendance{% endblock %}
{% block body_title %}Record attendance for session{% endblock %}

{% block content %}

{% if superuser_override %}
    <div class="alert alert-warning">
        <p>You are not a part of this Dojo. You are allowed access to this page because you are a superuser.</p>
        <p>Please be careful when changing attendance on Dojos you are not attending.</p>
    </div>
    <hr />
{% endif %}

<p>
    <strong>Session:</strong> {{ session }}<br />
    <strong>Ninjas enrolled:</strong> {{ object_list.count }}<br />
    <strong>Date:</strong> {{ session.start|date }}<br />
    <strong>Starts:</strong> {{ session.start|time }}<br />
</p>

<hr />

<p>{% bootstrap_icon "star" %} — Ninja has never attended a session before.</p>
<p>{% bootstrap_icon "user" %} — Ninja <strong>requires</strong> parental supervision.</p>

{% if object_list %}
    <table class="table">
        <tbody>
            {% for ninja_info in object_list %}
                <tr>
                    <td>
                        {{ ninja_info.ninja }}<br />
                        <span class="text-muted">
                            {% if ninja_info.ninja.not_attended_session %}
                                {% bootstrap_icon "star" %}
                            {% endif %}
                            {% if ninja_info.ninja.supervision_required %}
                                {% bootstrap_icon "user" %}
                            {% endif %}
                            age {{ ninja_info.ninja.age }} {{ ninja_info.ninja.get_gender_display|lower }}
                        </span>
                    </td>
                    <td class="col-md-1">
                        <a data-ninja-id="{{ ninja_info.ninja.id }}" class='btn btn-danger btn-undo {% if not ninja_info.attendance %}hidden{% endif %}'>Undo</a>
                        <a data-ninja-id="{{ ninja_info.ninja.id }}" class='btn btn-success btn-attending {% if ninja_info.attendance %}hidden{% endif %}'>Mark as Here</a>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% else %}
{% endif %}
{% endblock %}

{% block custom_js %}
    <script type="text/javascript" src="{% static 'js/jquery.filtertable.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/attendance.js' %}"></script>

    <script type="text/javascript">
    $('.btn-attending').click(function(ev) {
        mark_attendance(ev, '{% url 'attendance:record-ajax' %}', {{ session.id }}, true);
    })

    $('.btn-undo').click(function(ev) {
        mark_attendance(ev, '{% url 'attendance:record-ajax' %}', {{ session.id }}, false);
    })
    </script>

    <script type="text/javascript">
        $(document).ready(function () {

            $('table').filterTable({
                minRows: 0, // Always show the filter
                placeholder: 'search for ninjas',
                highlightClass: 'filter-cell'
            });
        });
    </script>
{% endblock %}