badges/urls.py
from django.conf.urls import patterns, url
from django.contrib import admin

import views

admin.autodiscover()

urlpatterns = patterns(
    '',
    url(r'^$', views.BadgeListView.as_view(), name='list'),
    url(r'^leaderboard/$', views.BadgeLeaderboard.as_view(), name='leaderboard'),
    url(r'^timeline/$', views.AwardTimeline.as_view(), name='timeline'),
)

dashboard/urls.py
from django.conf.urls import patterns, url

import views

urlpatterns = patterns(
    '',
    url(r'^$', views.DashboardView.as_view(), name='dashboard'),
)

dojo/urls.py
from django.conf.urls import patterns, url
from django.contrib import admin

import views

admin.autodiscover()

urlpatterns = patterns(
    '',
    url(r'^roles/$', views.RoleView.as_view(), name='roles'),
)

kanri/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings
from django.contrib import admin
from django.conf.urls.static import static

admin.autodiscover()

urlpatterns = patterns(
    '',
    url(r'^admin/', include(admin.site.urls)),
    url(r'^mentors/', include('mentors.urls', namespace='mentors')),
    url(r'^dojo/', include('dojo.urls', namespace='dojo')),
    url(r'^attendance/', include('attendance.urls', namespace='attendance')),
    url(r'^badges/', include('badges.urls', namespace='badges')),

    # Auth
    url(r'^login/', 'django.contrib.auth.views.login', name='login'),

    url(
        r'^logout/',
        'django.contrib.auth.views.logout_then_login',
        name='logout'
    ),

    # Dashboard app collects all other URLs
    url(r'', include('dashboard.urls', namespace='dashboard')),
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dashboard/models.py
from django.db import models

# Create your models here.

dashboard/views.py
from django.views import generic

import mentors
import ninjas


class DashboardView(generic.TemplateView):
    template_name = 'dashboard/dashboard.html'

    def get_context_data(self, *args, **kwargs):
        c = super(DashboardView, self).get_context_data(*args, **kwargs)
        try:
            c['mentor'] = mentors.models.Mentor.objects.get(
                user=self.request.user)
            c['parent'] = ninjas.models.Parent.objects.get(
                user=self.request.user)
            c['ninja'] = ninjas.models.Ninja.objects.get(
                user=self.request.user)
        except:
            pass
        return c

dashboard/templates/dashboard/dashboard.html
{% extends "base.html" %}

{% load fontawesome %}

{% block site_title %}Dashboard{% endblock %}
{% block body_title %}Hi, {{ user.get_full_name }}{% endblock %}

{% block content %}
    {% if mentor.approved_roles.all %}
        <h2>{% fontawesome_icon 'graduation-cap' color='green' %}
        You are a mentor <small>{{ mentor.approved_roles.all|join:', ' }}</small></h2>
        <p class="text-muted">
            You have been approved to volunteer at a dojo.
        </p>

        <p class="text-muted">
            If you have been asked to sign ninjas off as they enter the dojo, <a href="{% url 'attendance:list' %}">click here</a>.
        </p>
    {% elif mentor.applied_roles.all %}
        <h2>{% fontawesome_icon 'graduation-cap' color='orange' %}
        You have applied to be a mentor</h2>
        <p class="text-muted">
            Your application to volunteer at a dojo has not been actioned yet.
        </p>

        <p class="text-muted">
            If you want to review or change the roles you have applied for, <a href="{% url 'dojo:roles' %}">click here</a>.
        </p>
    {% else %}
        <h2>{% fontawesome_icon 'graduation-cap' color='red' %}
        You are not listed as a mentor</h2>
        <p class="text-muted">
            You have not applied to mentor at a Dojo.
        </p>
    {% endif %}

    <hr />

    {% if parent %}
        <h2>
            {% fontawesome_icon 'user' color='green' %}
            You are a parent
        </h2>
    {% else %}
        <h2>
            {% fontawesome_icon 'user' color='red' %}
            You are not listed as a parent
        </h2>
        <p class="text-muted">
            We can't find any children belonging to you on our system.
        </p>
    {% endif %}

    <hr />

    {% if ninja %}
        <h2>
            {% fontawesome_icon 'user' color='green' %}
            You are a ninja
        </h2>
    {% else %}
        <h2>
            {% fontawesome_icon 'user' color='red' %}
            You are not listed as a ninja
        </h2>
        <p class="text-muted">
            You have not registered to attend a dojo as a ninja.
        </p>

        <hr />
    {% endif %}


    {% if user.is_superuser %}
        <h2>
            {% fontawesome_icon 'user-secret' color='green' %}
            You are a superuser
        </h2>

        <p class="text-muted">
            You have unlimited read-write access to everything on the system,
            regardless of what roles you have been approved for.
        </p>

        <p class="text-muted">
            You can access the database backend <a href="{% url 'admin:index' %}">here</a>, but be warned,
            you can easily break things!
        </p>
    {% endif %}

{% endblock %}