dojo/urls.py
from django.conf.urls import patterns, url
from django.contrib import admin

import views

admin.autodiscover()

urlpatterns = patterns(
    '',
    url(r'^roles/$', views.RoleView.as_view(), name='roles'),
)

attendance/models.py
from django.db import models


class Attendance(models.Model):
    arrival = models.DateTimeField(
        help_text="When did the ninja arrive?",
        auto_now_add=True,
    )

    sighted_by = models.ForeignKey(
        'mentors.Mentor',
        help_text='Which mentor sighted this Ninja upon arrival and '
                  'ensured their safety and supervision?'
    )

    ninja = models.ForeignKey(
        'ninjas.Ninja',
        help_text='What ninjas is attending?',
    )

    session = models.ForeignKey(
        'dojo.Session',
        help_text='What session is the Ninja attending?',
    )

    def __str__(self):
        return "{s.ninja} attending {s.session}".format(s=self)

badges/models.py
from django.db import models


class Link(models.Model):
    name = models.CharField(
        max_length=50,
        unique=True,
        help_text="The link's human-readable name."
    )

    note = models.CharField(
        max_length=100,
        blank=True,
        help_text='An optional note about the link.'
    )

    url = models.URLField(
        blank=False,
        help_text="The URL."
    )

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['name']


class Category(models.Model):
    name = models.CharField(
        max_length=50,
        unique=True,
        help_text="The name of the category."
    )

    slug = models.SlugField(
        max_length=15,
        unique=True,
        help_text="A unique slug for the category."
    )

    image = models.ImageField(
        help_text="The category icon. Square transparent PNGs please.",
        blank=True,
    )

    links = models.ManyToManyField(
        'badges.Link',
        blank=True,
        help_text='A collection of relevant links (e.g. Codecademy '
                  'track URLs).'
    )

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['name']


class Badge(models.Model):
    name = models.CharField(
        max_length=30,
        unique=True,
        help_text="The badge's visible name"
    )

    slug = models.SlugField(
        max_length=30,
        unique=True,
        help_text="A unique slug for the badge."
    )

    image = models.ImageField(
        help_text="The badge icon. Square transparent PNGs please.",
        blank=True,
    )

    short_description = models.CharField(
        max_length=75,
        help_text="A short description of what this badge means, in the "
                  "past tense (e.g. this badge shows that you have...)"
    )

    requirements = models.TextField(
        max_length=4096,
        help_text="In-depth requirements. What do you need "
                  "to do to get this badge?"
    )

    order = models.PositiveSmallIntegerField(
        help_text='The order in which this badge will appear amongst other '
                  'badges in a list.',
        blank=False
    )

    categories = models.ManyToManyField(
        'badges.Category',
        help_text='The categories this badge belongs to.'
    )

    recipients = models.ManyToManyField(
        'ninjas.Ninja',
        through='badges.BadgeAward',
        help_text='The Ninjas that have received the badge.'
    )

    attachments = models.ManyToManyField(
        'badges.Attachment',
        blank=True,
        help_text='A collection of relevant attachments (e.g. worksheets).'
    )

    links = models.ManyToManyField(
        'badges.Link',
        blank=True,
        help_text='A collection of relevant links (e.g. Codecademy '
                  'track URLs).'
    )

    @property
    def relevant_links(self):
        return (Link.objects.filter(category=self.categories.all())
                | self.links.all())

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['order']


class Attachment(models.Model):
    name = models.CharField(
        max_length=50,
        unique=True,
        help_text="The attachment's human-readable name."
    )

    attachment = models.FileField(
        help_text="The attachment. Nothing too big, please!",
        blank=False
    )

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['name']


class BadgeAward(models.Model):
    timestamp = models.DateTimeField(
        auto_now_add=True,
        help_text="The time at which the badge was awarded."
    )

    notes = models.TextField(
        blank=True,
        help_text='Optional notes regarding the awarding of this '
                  'badge to this ninja.'
    )

    badge = models.ForeignKey(
        'badges.Badge',
        help_text='The badge to award.'
    )

    ninja = models.ForeignKey(
        'ninjas.Ninja',
        help_text='The Ninja to award the badge to.'
    )

    awarder = models.ForeignKey(
        'mentors.Mentor',
        help_text='The Mentor that awarded the badge to this Ninja.'
    )

    class Meta:
        unique_together = ['badge', 'ninja']
        ordering = ['-timestamp', 'ninja__user__first_name']

templates/base.html
{% load bootstrap3 %}
{% load staticfiles %}
{% load fontawesome %}

<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>{% block site_title %}Example{% endblock %} // Kanri</title>

    {% bootstrap_css %}
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

    <link rel="stylesheet" href="{% static 'css/custom.css' %}" />
    <link rel="stylesheet" href="{% static 'css/flash.css' %}" />
    <link href='//fonts.googleapis.com/css?family=Titillium+Web' rel='stylesheet' type='text/css'>
    {% fontawesome_stylesheet %}

    <link rel="icon" type="image/png" href="{% static 'img/coderdojo_logo_small.png' %}" />

    <!-- Page-specific CSS -->
    {% block custom_css %}
    {% endblock %}
</head>
<body>
<div id="wrap">
    <div class="container">
        <nav id="navbar" class="navbar navbar-default" role="navigation">
            <div class="container-fluid">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="{% url 'dashboard:dashboard' %}">
                        <span id="brand_text">Kanri</span>
                        <img class="hidden" src="{% static 'img/comssa_logo_128.png' %}" id="brand_logo" />
                    </a>
                </div>
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        {% if user.is_authenticated %}
                            <li><a href="{% url 'dashboard:dashboard' %}">Dashboard</a></li>
                        {% endif %}
                        {% if perms.attendance.add_attendance %}
                            <li><a href="{% url 'attendance:list' %}">Attendance</a></li>
                        {% endif %}
                        {% if perms.attendance.view_badge %}
                            <li><a href="{% url 'badges:list' %}">Badges</a></li>
                        {% endif %}
                        {% if user.is_staff %}
                            <li><a href="">Admin</a></li>
                        {% endif %}
                    </ul>
                    {% if user.is_authenticated %}
                        <ul class="nav navbar-nav navbar-right">
                            <li>
                                <a>{{ user.first_name }}</a>
                            </li>
                            <li>
                                <a class="glyphicon glyphicon-cog" href=""></a>
                            </li>
                        </ul>
                    {% else %}
                        <form method="post" action="{% url 'login' %}" class="navbar-form navbar-right">
                            {% csrf_token %}
                            <div class="form-group">
                                <input type="text" name="username" placeholder="Username" class="form-control">
                            </div>
                            <div class="form-group">
                                <input type="password" name="password" placeholder="Password" class="form-control">
                            </div>
                            <input type="hidden" name="next" value="{% url 'dashboard:dashboard' %}" />
                            <button type="submit" class="btn btn-success">Sign in</button>
                        </form>
                    {% endif %}
                </div><!--/.nav-collapse -->
            </div><!--/.container-fluid -->
        </nav>
    </div>

    <div class="container">

        <div class="page-header">
            <h1>
                {% block body_title %}Example{% endblock %}
            </h1>
        </div>
        {% if messages %}
            {% for message in messages %}
                <div class="alert alert-{{ message.tags }}">{{ message }}</div>
            {% endfor %}
            <hr />
        {% endif %}
        {% block content %}
            <p>This needs to be changed.</p>
        {% endblock %}
    </div>
    <div id="push"></div>
</div>

    <div id="footer">
        <div class="container" onmouseover="showCredits();" onmouseout="hideCredits();">
            <p id="footer_credits" class="hidden text-muted credit text-center">Kanri &copy; 2014 <a href="https://kye.id.au">Kye Russell</a>.
                Made for CoderDojo @ Curtin in Western Australia.
                <a href="https://github.com/KyeRussell/Kanri">Available on GitHub</a>.
            </p>
            <p id="footer_logo" class="text-muted credit text-center">
                <img src="{% static 'img/coderdojo_logo_small.png' %}" id="footer_logo" />
            </p>
        </div>
    </div>

    <script src="{% bootstrap_jquery_url %}"></script>
    <script src="{% static 'js/cheet.min.js' %}"></script>

    <!-- Shhhh. Only dreams now. -->
    <script type="text/javascript" src="{% static 'js/hidden.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/jquery.cookie.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/csrf.js' %}"></script>
    {% bootstrap_javascript %}

    <!-- Page-specific Javascript -->
    {% block custom_js %}
    {% endblock %}
</body>
</html>

templates/generic_delete.html
{% extends 'base.html' %}

{% load bootstrap3 %}

{% block site_title %}Delete {{ object }}{% endblock %}
{% block body_title %}Delete <b>{{ object }}</b>{% endblock %}

{% block content %}
<div class="well text-center">
	<h2>Are you sure you want to delete {{ object }}?</h2>
	<form method="post">
		{% csrf_token %}
		{% bootstrap_button 'Do it.' button_type="submit" button_class="btn-danger btn-lg" %}
	</form>
</div>
{% endblock %}

templates/generic_detail.html
{% extends "base.html" %}
{% load bootstrap3 %}
{% load name %}

{% block site_title %} Details for {{ object }} {% endblock %}
{% block body_title %} Details for <b>{{ object }}</b> {% endblock %}

{% block content %}
	{% block nocontrols %}

		{% block custom_buttons_before %} {% endblock %}

		{% block noedit %}
			<a href="{% block edit_url %}{% url 'home' %}{% endblock %}"class="btn btn-default">
				{% bootstrap_icon "pencil" %} Update {{ object }}
			</a>
		{% endblock %}
	
		{% block nodelete %}
			<a href="{% block delete_url %}{% url 'home' %}{% endblock %}" class="btn btn-default">
				{% bootstrap_icon "remove" %} Delete {{ object }}</a>
			</a>
		{% endblock %}
	
		{% block nolist %}
			<a href="{% block list_url %}{% url 'home' %}{% endblock %}" class="btn btn-default">
				{% bootstrap_icon "list" %} {{ object|class_name }} List</a>
			</a>
		{% endblock %}

		{% block custom_buttons_after %} {% endblock %}

		<hr />
	{% endblock %}

	<form class="form-horizontal" role="form">
		{% block detail %} {% endblock %}
	</form>
{% endblock %}

templates/generic_form.html
{% extends "base.html" %}
{% load bootstrap3 %}
{% load name %}

{% block site_title %}
	{% if object %}
		Edit
	{% else %}
		Add
	{% endif %}
	{{ view|model_name }}
{% endblock %}
{% block body_title %}<b>
	{% if object %}
		Edit
	{% else %}
		Add
	{% endif %}
	</b> {{ view|model_name }}
{% endblock %}

{% block content %}
<div class="row">
	<form action="" method="post" class="form form-horizontal">
		{% csrf_token %}
		{% bootstrap_form form layout="horizontal" %}
		{% buttons %}
			<div class="col-md-offset-2">
				{% with view|model_name as model_name %}
					{% if object %}
						{% with "Update "|add:model_name as edit_text %}
							{% bootstrap_button edit_text button_type="submit" %}
						{% endwith %}
						{% with "Delete "|add:model_name as delete_text %}
							{% bootstrap_button delete_text button_type="button" button_class="btn-danger" %}
						{% endwith %}
					{% else %}
						{% with "Add "|add:model_name as add_text %}
							{% bootstrap_button add_text button_type="submit" %}
						{% endwith %}
					{% endif %}
				{% endwith %}
				{% bootstrap_button "Clear" button_type="reset" %}
				{% if object %}

				{% endif %}
			</div>		
		{% endbuttons %}
	</form>
</div>
{% endblock %}

templates/generic_list.html
{% extends "base.html" %}
{% load bootstrap3 %}
{% load name %}

{% block site_title %} List of {{ view|model_name:True }} {% endblock %}
{% block body_title %} List of <b>{{ view|model_name:True }}</b> {% endblock %}

{% block content %}
	{% block nocontrols %}
		<div class="btn-group">
			{% block custom_buttons_before %} {% endblock %}
	
			{% block noadd %}
				<a href="{% block add_url %}{% url 'home' %}{% endblock %}"class="btn btn-default">
					{% bootstrap_icon "plus" %} Add {{ view|model_name }}
				</a>
			{% endblock %}
	
			{% block custom_buttons_after %} {% endblock %}
		</div>
		<hr />
	{% endblock %}

	{% if object_list %}
		<table class="table {% block custom_table_classes %}{% endblock %}">
			{% block list %} {% endblock %}
		</table>
	{% else %}
		<h2>There's nothing here...</h2>
	{% endif %}
{% endblock %}

templates/generic_panel.html
<div class="panel panel-default">
	<div class="panel-heading">
		<h3 class="panel-title">{% block panel_title %}Example Title{% endblock %}</h3>
	</div>
	<div class="panel-body">
		{% block panel_content %}Example content{% endblock %}
	</div>
</div>