badges/urls.py
from django.conf.urls import patterns, url
from django.contrib import admin

import views

admin.autodiscover()

urlpatterns = patterns(
    '',
    url(r'^$', views.BadgeListView.as_view(), name='list'),
    url(r'^leaderboard/$', views.BadgeLeaderboard.as_view(), name='leaderboard'),
    url(r'^timeline/$', views.AwardTimeline.as_view(), name='timeline'),
)

dojo/urls.py
from django.conf.urls import patterns, url
from django.contrib import admin

import views

admin.autodiscover()

urlpatterns = patterns(
    '',
    url(r'^roles/$', views.RoleView.as_view(), name='roles'),
)

badges/models.py
from django.db import models


class Link(models.Model):
    name = models.CharField(
        max_length=50,
        unique=True,
        help_text="The link's human-readable name."
    )

    note = models.CharField(
        max_length=100,
        blank=True,
        help_text='An optional note about the link.'
    )

    url = models.URLField(
        blank=False,
        help_text="The URL."
    )

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['name']


class Category(models.Model):
    name = models.CharField(
        max_length=50,
        unique=True,
        help_text="The name of the category."
    )

    slug = models.SlugField(
        max_length=15,
        unique=True,
        help_text="A unique slug for the category."
    )

    image = models.ImageField(
        help_text="The category icon. Square transparent PNGs please.",
        blank=True,
    )

    links = models.ManyToManyField(
        'badges.Link',
        blank=True,
        help_text='A collection of relevant links (e.g. Codecademy '
                  'track URLs).'
    )

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['name']


class Badge(models.Model):
    name = models.CharField(
        max_length=30,
        unique=True,
        help_text="The badge's visible name"
    )

    slug = models.SlugField(
        max_length=30,
        unique=True,
        help_text="A unique slug for the badge."
    )

    image = models.ImageField(
        help_text="The badge icon. Square transparent PNGs please.",
        blank=True,
    )

    short_description = models.CharField(
        max_length=75,
        help_text="A short description of what this badge means, in the "
                  "past tense (e.g. this badge shows that you have...)"
    )

    requirements = models.TextField(
        max_length=4096,
        help_text="In-depth requirements. What do you need "
                  "to do to get this badge?"
    )

    order = models.PositiveSmallIntegerField(
        help_text='The order in which this badge will appear amongst other '
                  'badges in a list.',
        blank=False
    )

    categories = models.ManyToManyField(
        'badges.Category',
        help_text='The categories this badge belongs to.'
    )

    recipients = models.ManyToManyField(
        'ninjas.Ninja',
        through='badges.BadgeAward',
        help_text='The Ninjas that have received the badge.'
    )

    attachments = models.ManyToManyField(
        'badges.Attachment',
        blank=True,
        help_text='A collection of relevant attachments (e.g. worksheets).'
    )

    links = models.ManyToManyField(
        'badges.Link',
        blank=True,
        help_text='A collection of relevant links (e.g. Codecademy '
                  'track URLs).'
    )

    @property
    def relevant_links(self):
        return (Link.objects.filter(category=self.categories.all())
                | self.links.all())

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['order']


class Attachment(models.Model):
    name = models.CharField(
        max_length=50,
        unique=True,
        help_text="The attachment's human-readable name."
    )

    attachment = models.FileField(
        help_text="The attachment. Nothing too big, please!",
        blank=False
    )

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['name']


class BadgeAward(models.Model):
    timestamp = models.DateTimeField(
        auto_now_add=True,
        help_text="The time at which the badge was awarded."
    )

    notes = models.TextField(
        blank=True,
        help_text='Optional notes regarding the awarding of this '
                  'badge to this ninja.'
    )

    badge = models.ForeignKey(
        'badges.Badge',
        help_text='The badge to award.'
    )

    ninja = models.ForeignKey(
        'ninjas.Ninja',
        help_text='The Ninja to award the badge to.'
    )

    awarder = models.ForeignKey(
        'mentors.Mentor',
        help_text='The Mentor that awarded the badge to this Ninja.'
    )

    class Meta:
        unique_together = ['badge', 'ninja']
        ordering = ['-timestamp', 'ninja__user__first_name']

badges/views.py
# from django.shortcuts import render
from django.views import generic
import models
import ninjas


class BadgeListView(generic.ListView):
    model = models.Category
    template_name = 'badges/list.html'


class BadgeLeaderboard(generic.ListView):
    model = ninjas.models.Ninja
    template_name = 'badges/leaderboard.html'


class AwardTimeline(generic.ListView):
    model = models.BadgeAward
    template_name = 'badges/timeline.html'

badges/templates/badges/leaderboard.html
{% extends "base.html" %}

{% block site_title %}Leaderboard{% endblock %}
{% block body_title %}Badge leaderboard{% endblock %}

{% block content %}

{% if object_list %}
    <table class="table">
        <thead>
            <tr>
                <th class='col-md-2'>Name</th>
                <th>Badges</th>
            </tr>
        </thead>
        <tbody>
            {% for ninja in object_list %}
                <tr>
                    <td>{{ ninja.user.get_full_name }}</td>
                    <td>
                        {% for badge in ninja.badge_set.all %}
                            <img data-toggle="tooltip" data-placement="top" title="{{ badge.name }}" class='badge-icon' src='{{ badge.image.url }}' />
                        {% endfor %}
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endif %}

{% endblock %}

{% block custom_js %}
    <script type="text/javascript">
        $('[data-toggle="tooltip"]').tooltip()
    </script>
{% endblock %}

badges/templates/badges/list.html
{% extends "base.html" %}

{% load fontawesome %}
dja
{% block site_title %}Badges{% endblock %}
{% block body_title %}Available badges{% endblock %}

{% block content %}
    {% if object_list %}
        <p>
            {% for object in object_list %}
                <a class="label label-primary" href="#{{ object.slug }}">{{ object.name }}</a> 
            {% endfor %}
        </p>
        <hr />
        {% for object in object_list %}
            <a name="{{ object.slug }}"></a>
            <h2>{{ object.name }}</h2>
            {% if object.badge_set.all %}
                {% for badge in object.badge_set.all %}
                    <div class="panel panel-default badge-panel">
                        <div class="panel-body">
                            <div class='col-md-2'>
                                <img src='{{ badge.image.url }}' />
                            </div>
                            <div class='col-md-9'>
                                <h3>{{ badge.name }}</h3>
                                <hr />
                                <p><strong>Recipients of this badge have</strong> {{ badge.short_description }}</p>
                                <hr />
                                <p>{{ badge.requirements }}</p>
                                {% if badge.attachments.all or badge.relevant_links %}
                                    <hr />
                                    <p>
                                    {% for attachment in badge.attachments.all %}
                                        {% fontawesome_icon 'file' %}
                                        <a href="{{ attachment.attachment.url }}" target="_blank">
                                            {{ attachment }}
                                            ({{ attachment.attachment.size|filesizeformat }})
                                        </a><br />
                                    {% endfor %}
                                    {% for link in badge.relevant_links %}
                                        {% fontawesome_icon 'link' %} 
                                        <a href="{{ link.url }}" target="_blank">{{ link }}</a>
                                        {% if link.note %}
                                            <span class="text-muted">{{ link.note }}</span>
                                        {% endif %}
                                        <br />
                                    {% endfor %}
                                    </p>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                {% endfor %}
            {% else %}
                <p class="text-danger">There are badges in this category.</p>
            {% endif %}
        {% endfor %}
    {% else %}
        <p class="text-danger">There are no categories.</p>
    {% endif %}
{% endblock %}

badges/templates/badges/timeline.html
{% extends "base.html" %}

{% block page_title %}Badge timeline{% endblock %}
{% block body_title %}Badge timeline{% endblock %}

{% block content %}
{% for award in object_list %}
    <div class="panel panel-default">
        <div class="panel-body">
            <div class="col-md-1">
                <img src="{{ award.badge.image.url }}" height="60px"/>
            </div>
            <h3>
                {{ award.ninja.user.get_full_name }}
                <span class="text-muted">has been awarded the</span>
                {{ award.badge.name }}
                <span class="text-muted">badge!</span> <small>{{ award.timestamp|timesince }} ago</small>
            </h3>
        </div>
    </div>
{% endfor %}
{% endblock %}